# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
#    four million, find the sum of the even-valued terms.
previous_num = 1
current_num = 2
next_num = 0

number_sequence = [1, 2]
even_numbers = [2]
while next_num < 4000000
  next_num = previous_num + current_num
  previous_num = current_num
  current_num = next_num
  number_sequence.push(next_num)
  if next_num%2 == 0
    even_numbers.push(next_num)
  end
end

puts number_sequence
puts "the even number sequence is:"
puts even_numbers
puts "the sum of the even numbers is:"
sum = 0
even_numbers.each do |number|
  sum = sum + number
end
puts sum
